# Generated by Django 2.2 on 2022-05-30 10:34

from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile)pic.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15, null=True, validators=[login.validators.validate_no_special_characters]),
        ),
    ]
