# Generated by Django 2.2 on 2022-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_image'),
        ('login', '0007_User_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=7, unique=True)),
                ('employee_branch', models.ForeignKey(on_delete='SET_NULL', related_name='employees', to='booking.Branch')),
            ],
        ),
    ]
