# Generated by Django 2.2 on 2022-05-24 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_dates', models.DateField()),
                ('booking_times', models.TimeField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '12:30'), (9, '13:00'), (10, '13:30'), (11, '14:00'), (12, '14:30'), (13, '15:00'), (14, '15:30')], default=None)),
                ('booking_dt_created', models.DateTimeField(auto_now_add=True)),
                ('booking_task', models.CharField(choices=[(1, '개인/가계 예금(수신)업무'), (2, '개인/가계 대출(여신)업무'), (3, '개인/가계 외환'), (4, '기업 예금(수신)업무'), (5, '기업 대출(여신)업무'), (6, '기업 외환')], max_length=20)),
                ('booking_etc', models.TextField()),
                ('booking_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Branch')),
                ('booking_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
