# Generated by Django 2.2 on 2022-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_task',
            field=models.IntegerField(choices=[(1, '개인/가계 예금(수신)업무'), (2, '개인/가계 대출(여신)업무'), (3, '개인/가계 외환'), (4, '기업 예금(수신)업무'), (5, '기업 대출(여신)업무'), (6, '기업 외환')], default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_times',
            field=models.IntegerField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '12:30'), (9, '13:00'), (10, '13:30'), (11, '14:00'), (12, '14:30'), (13, '15:00'), (14, '15:30')], default=None),
        ),
    ]
