# Generated by Django 2.2 on 2022-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220530_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_image',
            field=models.ImageField(blank=True, upload_to='branch_pics'),
        ),
    ]
