# Generated by Django 2.2 on 2022-06-08 11:55

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_branch_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_link',
            field=models.URLField(blank=True, validators=[booking.validators.validate_branch_link]),
        ),
    ]
