# Generated by Django 2.2 on 2022-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
    ]
