# Generated by Django 2.2 on 2022-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_image1',
            field=models.ImageField(blank=True, upload_to='booking_pics'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_image2',
            field=models.ImageField(blank=True, upload_to='booking_pics'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_image3',
            field=models.ImageField(blank=True, upload_to='booking_pics'),
        ),
    ]
