# Generated by Django 2.2 on 2022-06-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_booking_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_comments', to=settings.AUTH_USER_MODEL)),
                ('comment_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_comments', to='booking.Booking')),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
